version: "3.2"
services:
  db:
    image: mongo:4.0.4
    container_name: db
    restart: always
    ports:
      - ${DB_PORT}:27017
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
  api:
    image: node:14
    container_name: api
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules/
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    command: .docker/entrypoint.sh
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
